package com.sasuha.domain;

public enum AccountStatus {
	
	PENDING_VERFICATION,//aCCOUNT IS CREATED BUT NOT YET VERFIED
	ACTIVE,  //ACCOUNT IS ACTIVE IN GOOD STANDING
	SUSPENDED,//ACOOUNT IS TEMPORLA;Y SUSPENDES DUE TO VIOLATIONS
	DEACTIVATED,//ACOUNT S DEACTUVATED, USER MAY HAVE CHOOSEN TO DEACTIVATE
	BANNED,//ACCOUNT IS PERMANTLY BANNED DUE TO SERVER VIOLATIONS
	CLOSED//ACCOUNT IS PERMANTLY CLOSE PROBALBY USER REQUEST

}
